Ticket System/Models/ErrorViewModel.cs
using System;

namespace Ticket_System.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Ticket System/Models/bug_report.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ticket_System.Models
{
    [Table("bug_report")]
    public class bug_report
{
        [Key]
        public int id { get; set; }

        public string name { get; set; }

        public int state { get; set; }

        public int priority { get; set; }

        public string finish { get; set; }

        public string add_user { get; set; }

        public string edit_user { get; set; }
    }
}

Ticket System/Models/bug_report_detail.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ticket_System.Models
{
    [Table("bug_report_detail")]
    public class bug_report_detail
{
        [Key]
        public int id { get; set; }

        public int bug_report_id { get; set; }

        public string describe { get; set; }

        public string add_user { get; set; }

        public string edit_user { get; set; }
    }
}

Ticket System/Models/permission.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ticket_System.Models
{
    [Table("permission")]
    public class permission
{
        [Key]
        public int id { get; set; }

        public string name { get; set; }
    }
}

Ticket System/Models/require.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Ticket_System.Models
{
    [Table("require")]
    public class require
{
        [Key]
        public int id { get; set; }

        public string name { get; set; }

        public int state { get; set; }

        public string finish { get; set; }

        public string add_user { get; set; }

        public string edit_user { get; set; }
    }
}

Ticket System/Models/require_detail.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ticket_System.Models
{
    [Table("require_detail")]
    public class require_detail
    {
        [Key]
        public int id { get; set; }

        public int require_id { get; set; }

        public string describe {get;set;}

        public string finish { get; set; }

        public string add_user { get; set; }

        public string edit_user { get; set; }
    }
}

Ticket System/Models/use_case.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ticket_System.Models
{
    [Table("use_case")]
    public class use_case
{
        [Key]
        public int id { get; set; }

        public string name { get; set; }

        public int state { get; set; }

        public string finish { get; set; }

        public string add_user { get; set; }

        public string edit_user { get; set; }
    }
}

Ticket System/Models/use_case_detail.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ticket_System.Models
{
    [Table("use_case_detail")]
    public class use_case_detail
{
        [Key]
        public int id { get; set; }

        public int use_case_id { get; set; }

        public string describe { get; set; }

        public string add_user { get; set; }

        public string edit_user { get; set; }
    }
}

Ticket System/Models/user.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ticket_System.Models
{
    [Table("user")]
    public class user
    {
        [Key]
        public int id { get; set; }

        [Required(ErrorMessage ="請輸入帳號")]
        [StringLength(20, ErrorMessage = "輸入長度需小於20字元")]
        public string account { get; set; }

        [Required(ErrorMessage ="請輸入密碼")]
        [StringLength(20,ErrorMessage = "輸入長度需小於20字元")]
        public string password { get; set; }

        public int permission_id { get; set; }

        public string add_user { get; set; }
        
    }
}

Ticket System/Controllers/BUGController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Ticket_System.Models;


namespace Ticket_System.Controllers
{    
    public class BUGController : Controller
    {
        private readonly MyDbContext _dbContext;
        public BUGController(MyDbContext dbContext)
        {
            _dbContext = dbContext;
        }


        [HttpGet("Bug/user")]
        public IActionResult Index(string user)
        {
            using (_dbContext)
            {
                var user_permission_id =
                    (from u in _dbContext.user
                     join p in _dbContext.permission on u.permission_id equals p.id
                     where u.account == user
                     select p.id).ToList();

                ViewData["permission_id"] = user_permission_id[0];
                ViewData["User"] = user;
                ViewData["Page_Name"] = "BUG資料查詢頁面";
                ViewData["DataTable_Name"] = "查詢結果";

                List<bug_report> data = _dbContext.bug_report.ToList();                
                
                return View(data);
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ticket System/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Ticket_System.Models;

namespace Ticket_System.Controllers
{
    public class HomeController : Controller
    {
        private readonly MyDbContext _dbContext;
        public HomeController(MyDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet("user")]
        public IActionResult Index(string user)
        {
            using (_dbContext)
            {
                var user_permission_id =
                    (from u in _dbContext.user
                    join p in _dbContext.permission on u.permission_id equals p.id
                    where u.account == user
                    select p.id).ToList();

                ViewData["permission_id"] = user_permission_id[0];
                ViewData["User"] = user;
                return View();
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ticket System/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Ticket_System.Models;

namespace Ticket_System.Controllers
{
    public class LoginController : Controller
    {
        private readonly MyDbContext _dbContext;
        public LoginController(MyDbContext dbContext)
        {
            _dbContext = dbContext;
        }        

        public IActionResult Index()
        {
            var user = new user();
            string tMessage = TempData["Message"] as string;
            return View(user);
        }
        
        [HttpPost]
        public IActionResult Login(user user)
        {
            if (ModelState.IsValid)
            {
                using (_dbContext)
                {
                    var has = _dbContext.user.Where(x => x.account == user.account & x.password == user.password).Count();
                    user.password = "";                    

                    if (has > 0)
                    {
                        return RedirectToAction("Index", "Home", new { user = user.account });
                    }
                    else
                    {
                        TempData["Message"] = "帳號或密碼輸入錯誤";
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

Ticket System/Views/BUG/Index.cshtml
@model IEnumerable<Ticket_System.Models.bug_report>

<div class="container-fluid px-4">
    <h1 class="mt-4">@ViewData["Page_Name"]</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active"><a href="https://">新增</a></li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            @ViewData["DataTable_Name"]
        </div>
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>功能</th>
                        <th>標題</th>
                        <th>處理狀態</th>
                        <th>優先度</th>
                        <th>新增者</th>
                        <th>處理人員</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>功能</th>
                        <th>標題</th>
                        <th>處理狀態</th>
                        <th>優先度</th>
                        <th>新增者</th>
                        <th>處理人員</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td><a href="https://">編輯 </a><a href="https://"> 刪除</a></td>
                            <td>@item.name</td>
                            <td>@item.state</td>
                            <td>@item.priority</td>
                            <td>@item.add_user</td>
                            <td>@item.finish</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


@section Scripts{
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/script.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="~/js/datatables-simple-demo.js"></script>
}

Ticket System/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@section Scripts{
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/script.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="~/js/datatables-simple-demo.js"></script>
}

Ticket System/Views/Login/Index.cshtml
@{
    Layout = null;
}

@model Ticket_System.Models.user

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link href="~/css/style.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    <title>登入</title>
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                <div class="card-body">
                                    <form asp-action="Login" method="post">
                                        <span class="text-danger">@TempData["Message"]</span>
                                        <div class="form-floating mb-3">
                                            <input class="form-control" id="account" asp-for="@Model.account" type="text" formnovalidate />
                                            <label for="inputEmail">帳號</label>
                                            <span asp-validation-for="@Model.account" class="text-danger"></span>
                                        </div>
                                        <div class="form-floating mb-3">
                                            <input class="form-control" id="password" asp-for="@Model.password" type="password" />
                                            <label for="inputPassword">密碼</label>
                                            <span asp-validation-for="@Model.password" class="text-danger"></span>
                                        </div>
                                        <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                            <input class="btn btn-primary" type="submit" value="登入" />
                                        </div>
                                    </form>
                                </div>
                                <div class="card-footer text-center py-3">
                                    <div class="small"><a href="register.html">註冊</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2021</div>                        
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.0.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

Ticket System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Ticket_System</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">

    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" asp-controller="Home" asp-action="Index" asp-route-User="@ViewData["User"]">Tick System</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0"></form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    @*<li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>*@
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        @switch (ViewData["permission_id"].ToString())
                        {
                            case "1":  //QA
                                {
                                    <a class="nav-link" asp-controller="BUG" asp-action="Index" asp-route-user="@ViewData["User"]">
                                        BUG
                                    </a>
                                    <a class="nav-link" href="index.html">
                                        測試案例
                                    </a>
                                    break;
                                }
                            case "2":  //RD
                                {
                                    <a class="nav-link" href="index.html">
                                        BUG
                                    </a>
                                    <a class="nav-link" href="index.html">
                                        功能要求
                                    </a>
                                    <a class="nav-link" href="index.html">
                                        測試案例
                                    </a>
                                    break;
                                }
                            case "3":  //PM
                                {
                                    <a class="nav-link" href="index.html">
                                        測試案例
                                    </a>
                                    <a class="nav-link" href="index.html">
                                        功能要求
                                    </a>
                                    break;
                                }
                            case "4":  //Admin
                                {
                                    <a class="nav-link" href="index.html">
                                        BUG
                                    </a>
                                    <a class="nav-link" href="index.html">
                                        測試案例
                                    </a>
                                    <a class="nav-link" href="index.html">
                                        功能要求
                                    </a>
                                    <a class="nav-link" href="index.html">
                                        新增帳號
                                    </a>
                                    break;
                                }

                        }
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:@ViewData["User"]</div>
                    Tick System
                </div>
            </nav>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2021</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2021</div>                       
                    </div>
                </div>
            </footer>
        </div>
    </div>

    @RenderSection("Scripts", required: false)

</body>
</html>